#!/usr/bin/python
import rospy
import rospkg
import os

if __name__ == "__main__":
	rospack = rospkg.RosPack()
	prefix = rospack.get_path('cob_read_text_data')
	path1 = os.path.join(*[prefix, 'dictionary', 'full-dictionary'])
	path2 = os.path.join(*[prefix, 'dictionary', 'new-dictionary'])
	fobj1 = open(path1, "r")
	fobj2 = open(path2, "w")
	for line in fobj1: 
		fobj2.write(" " + line) 
	fobj1.close()
	fobj2.close()
